# Use a lightweight web server image as the base
FROM nginx:alpine

# Copy the frontend source code to the default Nginx public directory
COPY ./public /usr/share/nginx/html

# Expose the default Nginx port
EXPOSE 80

# No need for CMD as Nginx will automatically start
